In [22]:
import pandas as pd
Location = "Desktop\POP01.xls"

In [23]:
df = pd.read_excel(Location)

In [24]:
df.head(10)

,Area_name,STCOU,POP010130F,POP010130D,POP010130N1,POP010130N2,POP010140F,POP010140D,POP010140N1,POP010140N2,...,POP010200N1,POP010200N2,POP010210F,POP010210D,POP010210N1,POP010210N2,POP020170F,POP020170D,POP020170N1,POP020170N2
0,UNITED STATES,0,0,123202624,0,0,0,132164569,0,0,...,0,0,0,308745538,0,0,0,203302020,0,0
1,ALABAMA,1000,0,2646248,0,0,0,2832961,0,0,...,0,0,0,4779736,0,0,0,3444354,0,0
2,"Autauga, AL",1001,0,19694,0,0,0,20977,0,0,...,0,0,0,54571,0,0,0,24460,0,0
3,"Baldwin, AL",1003,0,28289,0,0,0,32324,0,0,...,0,0,0,182265,0,0,0,59382,0,0
4,"Barbour, AL",1005,0,32425,0,0,0,32722,0,0,...,0,0,0,27457,0,0,0,22543,0,0
5,"Bibb, AL",1007,0,20780,0,0,0,20155,0,0,...,0,0,0,22915,0,0,0,13812,0,0
6,"Blount, AL",1009,0,28020,0,0,0,29490,0,0,...,0,0,0,57322,0,0,0,26853,0,0
7,"Bullock, AL",1011,0,20016,0,0,0,19810,0,0,...,0,0,0,10914,0,0,0,11824,0,0
8,"Butler, AL",1013,0,30195,0,0,0,32447,0,0,...,0,0,0,20947,0,0,0,22007,0,0
9,"Calhoun, AL",1015,0,55611,0,0,0,63319,0,0,...,0,0,0,118572,0,0,0,103092,0,0