In [32]:
import pandas as pd
import numpy as np
import glob
all_data = pd.DataFrame()
for f in glob.glob("Desktop/datasets/weekly_call_data/weekdata_*.xlsx"):
    df = pd.read_excel(f)
    all_data = all_data.append(df,ignore_index=True)
all_data.describe()
df.head(10)

,Unnamed: 0,CallingNumber,DayOfWeek,TimeOfDay,CallDuration,ReasonForCall,AnsweringAgent
0,0,141-471-0978,tue,09:06,14,Technical Support,Nicki
1,1,316-174-6528,tue,12:06,8,Technical Support,Maria
2,2,310-757-1063,fri,11:53,21,Return,Kennedy
3,3,206-612-2605,mon,10:56,5,Complaint,Roland
4,4,127-215-2713,fri,15:59,24,Return,Gregory
5,5,998-514-0931,thu,15:54,10,Complaint,Lisa
6,6,658-861-9467,fri,12:11,15,Return,Dawn
7,7,930-688-5234,fri,13:18,5,Return,Maria
8,8,210-138-4058,wed,10:45,9,Technical Support,Gregory
9,9,436-627-2578,wed,09:45,8,Technical Support,Dawn